// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => const FirebaseOptions(
    apiKey: 'AIzaSyCPSiSnu4yS3kI4pSD0lijV-wcuv2DaGlY',
    appId: '1:1049042700396:android:a3277f1a55e2447d447049',
    messagingSenderId: '1049042700396',
    projectId: 'targets-away',
    storageBucket: 'targets-away.firebasestorage.app',
  );
}